import { Product, ProductDetail } from "@/types/product";

const productDetails: ProductDetail[] = [
  {
    id: "1",
    name: "eSIM Nhật Bản 7 ngày - 3GB/ngày",
    slug: "esim-nhat-ban-7-ngay-3gb",
    image: "https://picsum.photos/seed/esim-japan/600/600",
    images: [
      "https://picsum.photos/seed/esim-japan/600/600",
      "https://picsum.photos/seed/esim-japan-2/600/600",
      "https://picsum.photos/seed/esim-japan-3/600/600",
      "https://picsum.photos/seed/esim-japan-4/600/600",
    ],
    sku: "ESIM-JP-7D-3GB",
    price: 200000,
    salePrice: 150000,
    originalPrice: 200000,
    stock: 50,
    category: "eSIM Du lịch",
    categoryId: "esim",
    inStock: true,
    badge: "-25%",
    description: "Gói eSIM du lịch Nhật Bản 7 ngày với 3GB data tốc độ cao mỗi ngày. Kích hoạt tức thì, không cần đổi SIM.",
    longDescription: "Trải nghiệm kết nối internet tốc độ cao tại Nhật Bản với gói eSIM 7 ngày. Mỗi ngày bạn được sử dụng 3GB data 4G/LTE tốc độ cao, sau đó giảm tốc độ xuống 128Kbps. Hỗ trợ tất cả các thiết bị tương thích eSIM. Kích hoạt đơn giản qua QR code, không cần đổi SIM vật lý. Phủ sóng toàn bộ lãnh thổ Nhật Bản bao gồm Tokyo, Osaka, Kyoto và các vùng nông thôn.",
  },
  {
    id: "2",
    name: "eSIM Hàn Quốc 5 ngày - Unlimited",
    slug: "esim-han-quoc-5-ngay",
    image: "https://picsum.photos/seed/esim-korea/600/600",
    images: [
      "https://picsum.photos/seed/esim-korea/600/600",
      "https://picsum.photos/seed/esim-korea-2/600/600",
      "https://picsum.photos/seed/esim-korea-3/600/600",
    ],
    sku: "ESIM-KR-5D-UNL",
    price: 250000,
    stock: 30,
    category: "eSIM Du lịch",
    categoryId: "esim",
    inStock: true,
    badge: "Hot",
    description: "Data không giới hạn tại Hàn Quốc trong 5 ngày. Tốc độ 4G LTE ổn định, phủ sóng toàn quốc.",
    longDescription: "Gói eSIM Hàn Quốc 5 ngày Unlimited mang đến trải nghiệm internet không giới hạn. Sử dụng mạng 4G LTE của SK Telecom - nhà mạng lớn nhất Hàn Quốc. Phù hợp cho du lịch, công tác, livestream và sử dụng bản đồ. Kích hoạt ngay khi quét QR code tại sân bay.",
  },
  {
    id: "3",
    name: "Thẻ Viettel 100K",
    slug: "the-viettel-100k",
    image: "https://picsum.photos/seed/viettel100/600/600",
    images: [
      "https://picsum.photos/seed/viettel100/600/600",
      "https://picsum.photos/seed/viettel100-2/600/600",
    ],
    sku: "VTT-100K",
    price: 100000,
    salePrice: 95000,
    originalPrice: 100000,
    stock: 200,
    category: "Thẻ Viễn thông",
    categoryId: "the-nap",
    inStock: true,
    description: "Thẻ nạp Viettel mệnh giá 100.000đ. Nhận mã thẻ ngay sau khi thanh toán.",
    longDescription: "Thẻ nạp Viettel mệnh giá 100.000đ dùng để nạp tiền vào tài khoản di động Viettel. Mã thẻ được gửi tức thì qua email và SMS sau khi thanh toán thành công. Có thể sử dụng để nạp cho bất kỳ số thuê bao Viettel nào.",
  },
  {
    id: "4",
    name: "eSIM Thái Lan 10 ngày - 5GB/ngày",
    slug: "esim-thai-lan-10-ngay",
    image: "https://picsum.photos/seed/esim-thai/600/600",
    images: [
      "https://picsum.photos/seed/esim-thai/600/600",
      "https://picsum.photos/seed/esim-thai-2/600/600",
      "https://picsum.photos/seed/esim-thai-3/600/600",
    ],
    sku: "ESIM-TH-10D-5GB",
    price: 320000,
    stock: 0,
    category: "eSIM Du lịch",
    categoryId: "esim",
    inStock: false,
    description: "Gói eSIM Thái Lan 10 ngày, 5GB data mỗi ngày. Phủ sóng Bangkok, Phuket, Chiang Mai.",
    longDescription: "Khám phá Thái Lan với gói eSIM 10 ngày - 5GB/ngày. Tốc độ 4G LTE ổn định trên mạng AIS và DTAC. Phủ sóng toàn bộ các điểm du lịch nổi tiếng: Bangkok, Phuket, Chiang Mai, Pattaya. Hỗ trợ hotspot chia sẻ.",
  },
  {
    id: "5",
    name: "Thẻ Game Garena 200K",
    slug: "the-game-garena-200k",
    image: "https://picsum.photos/seed/garena200/600/600",
    images: [
      "https://picsum.photos/seed/garena200/600/600",
      "https://picsum.photos/seed/garena200-2/600/600",
    ],
    sku: "GRN-200K",
    price: 200000,
    stock: 100,
    category: "Thẻ Game",
    categoryId: "the-game",
    inStock: true,
    description: "Thẻ nạp Garena 200K dùng cho Liên Quân Mobile, Free Fire và các game Garena khác.",
    longDescription: "Thẻ Garena mệnh giá 200.000đ. Sử dụng để nạp Garena Shells, dùng trong Liên Quân Mobile, Free Fire, FIFA Online 4 và tất cả game trên nền tảng Garena. Mã thẻ gửi ngay sau thanh toán.",
  },
  {
    id: "6",
    name: "eSIM Singapore 3 ngày - Unlimited",
    slug: "esim-singapore-3-ngay-unlimited",
    image: "https://picsum.photos/seed/esim-sg/600/600",
    images: [
      "https://picsum.photos/seed/esim-sg/600/600",
      "https://picsum.photos/seed/esim-sg-2/600/600",
    ],
    sku: "ESIM-SG-3D-UNL",
    price: 180000,
    stock: 40,
    category: "eSIM Du lịch",
    categoryId: "esim",
    inStock: true,
    badge: "Mới",
    description: "Gói eSIM Singapore 3 ngày Unlimited data. Tốc độ 4G LTE, kích hoạt tức thì.",
    longDescription: "Gói eSIM Singapore 3 ngày với data không giới hạn. Sử dụng mạng Singtel - nhà mạng lớn nhất Singapore.",
  },
  {
    id: "7",
    name: "Data Mobifone 30GB/tháng",
    slug: "data-mobifone-30gb",
    image: "https://picsum.photos/seed/mobifone/600/600",
    images: ["https://picsum.photos/seed/mobifone/600/600"],
    sku: "DATA-MB-30GB",
    price: 90000,
    salePrice: 77000,
    originalPrice: 90000,
    stock: 150,
    category: "Data 4G/5G",
    categoryId: "data",
    inStock: true,
    description: "Gói data Mobifone 30GB/tháng. Giảm 15% so với mua trực tiếp.",
    longDescription: "Gói data Mobifone 30GB sử dụng trong 30 ngày.",
  },
  {
    id: "8",
    name: "eSIM Đài Loan 7 ngày - Unlimited",
    slug: "esim-dai-loan-7-ngay",
    image: "https://picsum.photos/seed/esim-taiwan/600/600",
    images: [
      "https://picsum.photos/seed/esim-taiwan/600/600",
      "https://picsum.photos/seed/esim-taiwan-2/600/600",
    ],
    sku: "ESIM-TW-7D-UNL",
    price: 179000,
    stock: 20,
    category: "eSIM Du lịch",
    categoryId: "esim",
    inStock: true,
    description: "Gói eSIM Đài Loan 7 ngày Unlimited data.",
    longDescription: "Gói eSIM Đài Loan 7 ngày với data không giới hạn.",
  },
  {
    id: "9",
    name: "eSIM Úc 10 ngày - 4GB/ngày",
    slug: "esim-uc-10-ngay",
    image: "https://picsum.photos/seed/esim-aus/600/600",
    images: [
      "https://picsum.photos/seed/esim-aus/600/600",
      "https://picsum.photos/seed/esim-aus-2/600/600",
    ],
    sku: "ESIM-AU-10D-4GB",
    price: 249000,
    stock: 25,
    category: "eSIM Du lịch",
    categoryId: "esim",
    inStock: true,
    description: "Gói eSIM Úc 10 ngày, 4GB data mỗi ngày.",
    longDescription: "Gói eSIM Australia 10 ngày với 4GB data mỗi ngày.",
  },
  {
    id: "10",
    name: "Thẻ Vinaphone 200K",
    slug: "the-vinaphone-200k",
    image: "https://picsum.photos/seed/vinaphone/600/600",
    images: ["https://picsum.photos/seed/vinaphone/600/600"],
    sku: "VNP-200K",
    price: 190000,
    stock: 80,
    category: "Thẻ Viễn thông",
    categoryId: "the-nap",
    inStock: true,
    description: "Thẻ nạp Vinaphone mệnh giá 200.000đ.",
    longDescription: "Thẻ nạp Vinaphone mệnh giá 200.000đ.",
  },
  {
    id: "11",
    name: "eSIM Châu Âu 15 ngày - 5GB/ngày",
    slug: "esim-chau-au-15-ngay",
    image: "https://picsum.photos/seed/esim-eu/600/600",
    images: [
      "https://picsum.photos/seed/esim-eu/600/600",
      "https://picsum.photos/seed/esim-eu-2/600/600",
    ],
    sku: "ESIM-EU-15D-5GB",
    price: 399000,
    stock: 15,
    category: "eSIM Du lịch",
    categoryId: "esim",
    inStock: true,
    description: "Gói eSIM Châu Âu 15 ngày, 5GB/ngày.",
    longDescription: "Gói eSIM Châu Âu 15 ngày với 5GB data mỗi ngày. Phù sóng 30+ quốc gia EU.",
  },
  {
    id: "12",
    name: "Thẻ Game Steam 500K",
    slug: "the-steam-500k",
    image: "https://picsum.photos/seed/steam/600/600",
    images: ["https://picsum.photos/seed/steam/600/600"],
    sku: "STM-500K",
    price: 475000,
    stock: 50,
    category: "Thẻ Game",
    categoryId: "the-game",
    inStock: true,
    description: "Thẻ nạp Steam Wallet 500K.",
    longDescription: "Thẻ Steam Wallet mệnh giá 500.000đ.",
  },
];

export async function getProductBySlug(slug: string): Promise<ProductDetail | null> {
  return productDetails.find((p) => p.slug === slug) ?? null;
}

export async function getRelatedProducts(
  categoryId: string,
  excludeId: string
): Promise<Product[]> {
  return productDetails
    .filter((p) => p.categoryId === categoryId && p.id !== excludeId)
    .slice(0, 4)
    .map(({ images, sku, salePrice, stock, categoryId, longDescription, ...product }) => product);
}
