import { Product } from "@/types/product";

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "eSIM Nhật Bản 7 ngày - 3GB/ngày",
    slug: "esim-nhat-ban-7-ngay-3gb",
    image: "https://picsum.photos/seed/esim-japan/400/300",
    price: 150000,
    originalPrice: 200000,
    category: "eSIM Du lịch",
    inStock: true,
  },
  {
    id: "2",
    name: "eSIM Hàn Quốc 5 ngày - Unlimited Data",
    slug: "esim-han-quoc-5-ngay-unlimited",
    image: "https://picsum.photos/seed/esim-korea/400/300",
    price: 250000,
    originalPrice: 300000,
    category: "eSIM Du lịch",
    inStock: true,
    badge: "Hot",
  },
  {
    id: "3",
    name: "Thẻ Viettel 100K",
    slug: "the-viettel-100k",
    image: "https://picsum.photos/seed/viettel/400/300",
    price: 95000,
    originalPrice: 100000,
    category: "Thẻ Viễn thông",
    inStock: true,
  },
  {
    id: "4",
    name: "eSIM Thái Lan 10 ngày - 5GB/ngày",
    slug: "esim-thai-lan-10-ngay-5gb",
    image: "https://picsum.photos/seed/esim-thai/400/300",
    price: 320000,
    category: "eSIM Du lịch",
    inStock: true,
  },
  {
    id: "5",
    name: "Thẻ Game Garena 200K",
    slug: "the-game-garena-200k",
    image: "https://picsum.photos/seed/garena/400/300",
    price: 200000,
    category: "Thẻ Game",
    inStock: false,
  },
  {
    id: "6",
    name: "eSIM Châu Âu 15 ngày - 10GB tổng",
    slug: "esim-chau-au-15-ngay-10gb",
    image: "https://picsum.photos/seed/esim-eu/400/300",
    price: 450000,
    originalPrice: 550000,
    category: "eSIM Du lịch",
    inStock: true,
  },
  {
    id: "7",
    name: "Thẻ Mobifone 50K",
    slug: "the-mobifone-50k",
    image: "https://picsum.photos/seed/mobifone/400/300",
    price: 47000,
    originalPrice: 50000,
    category: "Thẻ Viễn thông",
    inStock: true,
  },
  {
    id: "8",
    name: "eSIM Singapore 3 ngày - Unlimited",
    slug: "esim-singapore-3-ngay-unlimited",
    image: "https://picsum.photos/seed/esim-sg/400/300",
    price: 180000,
    category: "eSIM Du lịch",
    inStock: false,
    badge: "Mới",
  },
];
